services:
gedmo.listener.sortable:
        class: Gedmo\Sortable\SortableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]

# stof_doctrine_extensions:
#     class:
#         loggable: ActivityLogBundle\Listener\LoggableListener
#     orm:
#         default:
#             loggable: true