fos_ck_editor:
    base_path: "fosckeditor"
    js_path:   "fosckeditor/ckeditor.js"


    configs:
        my_config:
            toolbar: [
               [ 'Source','-','Save','NewPage','DocProps','Preview','Print','-','Templates' ],"-",
               [ 'Cut','Copy','Paste','PasteText','PasteFromWord','-','Undo','Redo' ],"-",
               [ 'Find','Replace','-','SelectAll','-','SpellChecker', 'Scayt' ],"-",
               { name: 'styles', items : [ 'Styles','Format','Font','FontSize' ] },
               '/',
               { name: 'basicstyles', items : [ 'Bold','Italic','Underline','Strike','Subscript','Superscript','-','RemoveFormat' ] },
               { name: 'paragraph', items : [ 'NumberedList','BulletedList','-','Outdent','Indent','-','Blockquote','CreateDiv','-','JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock','-','BidiLtr','BidiRtl' ] },
               { name: 'links', items : [ 'Link','Unlink','Anchor' ] },
               { name: 'insert', items : [ 'Image','Table','HorizontalRule','Smiley','SpecialChar','PageBreak' ] },
               '-',
               { name: 'colors', items : [ 'TextColor','BGColor' ] },
               { name: 'tools', items : [ 'Maximize', 'ShowBlocks' ] }
              ]
            uiColor:                "#cccccc"
            filebrowserUploadRoute: "file_uploader"
            filebrowserBrowseRoute: "file_browser"
            extraPlugins: "wordcount"
    plugins:
        wordcount:
            path:     "/wordcount/"
            filename: "plugin.js"
