 
lexik_form_filter:
    listeners:
        doctrine_orm: true
        doctrine_dbal: false
        doctrine_mongodb: false
    force_case_insensitivity: false
    encoding: ~ # Encoding for case insensitive LIKE comparisons. For example: UTF-8
    where_method: ~  # null | and | or
    condition_pattern: text.starts

# lexik_translation:
#     fallback_locale: [en]         # (required) default locale(s) to use
#     managed_locales: [en, fr, de] 


#     exporter:
#         use_yml_tree: false
#     base_layout: "LexikTranslationBundle::layout.html.twig"

#     grid_input_type: text       # text|textarea
#     grid_toggle_similar: false
#     resources_registration:
#         type:                 all  # all | files | database
#         managed_locales_only: true

